# Generated by Django 3.1.4 on 2020-12-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mizi_app', '0002_auto_20201212_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='url',
        ),
    ]
