# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-12-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizi_app', '0008_auto_20201215_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
