# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-01-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizi_app', '0010_auto_20201228_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
